version: 0.0
os: linux

files:
  - soure: /
    destination: /webapps/goapp/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timiout: 3600
      # runas: root
      runas: ec2-user
  AfterInstall:
    - locagion: scripts/after_install.sh
      timiout: 3600
      # runas: root
      runas: ec2-user
  ApplicationStart:
    - locagion: scripts/application_start.sh
      timiout: 3600
      # runas: root
      runas: ec2-user
