version: 0.0
os: linux

files:
  - source: step-03/
    destination: /webapps/goapp/

hooks:
  ApplicationStop:
    - location: step-03/scripts/application_stop.sh
      timiout: 20
      runas: root
      # runas: ec2-user
  BeforeInstall:
    - location: step-03/scripts/before_install.sh
      timiout: 20
      runas: root
      # runas: ec2-user
  AfterInstall:
    - location: step-03/scripts/after_install.sh
      timiout: 20
      runas: root
      # runas: ec2-user
  ApplicationStart:
    - location: step-03/scripts/application_start.sh
      timiout: 20
      runas: root
      # runas: ec2-user
